import { SITE_NAME } from '../content/scene';

/** Interface labels only. Facts and scene text live in `src/content/`. */
export const UI = {
  openPage: (label: string) => `Open ${label}`,
  openItem: (label: string, pageLabel: string) => `Open ${label} in ${pageLabel}`,
  back: 'Back',
  mute: 'Mute',
  menu: 'Menu',
  menuLabel: 'Sections',
  loading: 'Loading',
  pageTitle: (label: string) => `${label} · ${SITE_NAME}`,
  education: 'Education',
  coursework: 'Coursework',
  location: 'Location',
  links: 'Links',
  email: 'Email',
  copyEmail: 'Copy email',
  copied: 'Copied.',
  copyFailed: 'Copy failed. The address is selected; copy it with your keyboard.',
  mailApp: 'Open in mail app',
  authors: 'Authors:',
  openOnXplore: 'Open on IEEE Xplore',
  doiLink: (doi: string) => `DOI: ${doi}`,
  summary: 'Summary',
  contribution: 'Contribution',
  pipeline: 'Pipeline',
  results: 'Results',
  resultsTable: 'Results per dataset',
  resultColumns: ['Dataset', 'Description', 'Precision', 'Recall', 'mAP@50', 'mAP@50:95'] as const,
  adrContext: 'Context:',
  adrDecision: 'Decision:',
  adrConsequences: 'Consequences:',
  bibtex: 'BibTeX',
  copyBibtex: 'Copy BibTeX',
  copyBibtexFailed: 'Copy failed. The BibTeX is selected; copy it with your keyboard.',
};
